### ISSUE TITLE
Support for Yarn 4

### ISSUE THREAD

**Issue by IchordeDionysos** [dropseed/deps-js#41]
Does deps support Yarn 4?
At least when I tried to run it I got this error:

<details><summary>Details</summary>
<p>

```shell
> deps upgrade --verbose
> No local config found, detecting your dependencies automatically
---
version: 3
dependencies:
- type: js
  path: .

---
> Using component from https://github.com/dropseed/deps-js
> Storing component in /Users/user/Library/Caches/deps/components/deps-js
> git pull
Already up to date.
> Skipping install of /Users/user/Library/Caches/deps/components/deps-js
> Collecting with /Users/user/Library/Caches/deps/components/deps-js...
> Input path: .
> RUN_AS=collector node $DEPS_COMPONENT_PATH/build/entrypoint.js . /var/folders/9l/yxmlk4dj2ll5vjt28_70kvvw0000gn/T/deps-450768166
.
Loading manifest from .
exec cd . && yarn workspaces info --json { silent: true }
Unable to find additional manifests
exec cd . && npm outdated --json { silent: true }
Loading manifest from /Users/user/develop/yarn_4_project
exec cd /Users/user/develop/yarn_4_project && yarn workspaces info --json { silent: true }
Unable to find additional manifests
Converting yarn.lock to lockfile in dependencies-schema
/Users/user/Library/Caches/deps/components/deps-js/node_modules/@yarnpkg/lockfile/index.js:5064
    throw new SyntaxError(`${msg} ${this.token.line}:${this.token.col} in ${this.fileLoc}`);
    ^

SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/Users/user/Library/Caches/deps/components/deps-js/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/Users/user/Library/Caches/deps/components/deps-js/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/Users/user/Library/Caches/deps/components/deps-js/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at module.exports.exports.default (/Users/user/Library/Caches/deps/components/deps-js/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at Lockfile.convertYarnLockToSchema (/Users/user/Library/Caches/deps/components/deps-js/build/lockfile.js:146:46)
    at Lockfile.convertToSchema (/Users/user/Library/Caches/deps/components/deps-js/build/lockfile.js:133:21)
    at collect (/Users/user/Library/Caches/deps/components/deps-js/build/collect.js:33:35)
    at Object.<anonymous> (/Users/user/Library/Caches/deps/components/deps-js/build/entrypoint.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v20.11.0
exit status 1

```

</p>
</details>

**Comment by davegaeddert** [comment]
Hey @IchordeDionysos — you're right, it wasn't working for v4. I took at stab at it and you're welcome to try running it again. Unfortunately I need to rework some of the testing setup to test all these different versions of the package managers themselves, but in my local test it does work. Let me know, thanks!
